export default [
    {
        name: 'markup',
        type: 'icon',
        icon: 'html5',
        toggle: true
    }, {
        name: 'style',
        type: 'icon',
        icon: 'css3',
        toggle: true
    }, {
        name: 'script',
        type: 'icon',
        icon: 'code',
        toggle: true
    }, {
        type: 'space'
    }, {
        type: 'icon',
        icon: 'plus'
    }, {
        type: 'icon',
        icon: 'download'
    }, {
        name: 'fullscreen',
        type: 'icon',
        icon: 'arrows-alt'
    }, {
        type: 'icon',
        icon: 'magic'
    }, {
        type: 'space'
    }, {
        type: 'icon',
        icon: 'refresh',
        toggle: false
    }, {
        type: 'icon',
        icon: 'play'
    }, {
        type: 'expand'
    }, {
        type: 'icon',
        icon: 'user'
    }, {
        type: 'icon',
        icon: 'cog'
    }, {
        type: 'icon',
        icon: 'question-circle'
    }, {
        type: 'text',
        text: 'Codemagic',
        brand: true
    }
];
